apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  mongodb.host: "mongodb-service"
  mongodb.port: "27017"
  redis.host: "redis-service"
  redis.port: "6379"
  kafka.bootstrap.servers: "kafka-service:9092"

